services:
  jamjamnow-api-service:
  build:
    context: .
    dockerfile: api-service.Dockerfile
  image: jamjamnow-api-service-img
  restart: always
  ports:
    - '${API_SERVER_PORT}:${API_SERVER_PORT}'
  environment:
    - ACTIVE_PROFILE=${ACTIVE_PROFILE}
    - API_SERVER_PORT=${API_SERVER_PORT}
    - DB_ENDPOINT=${DB_ENDPOINT}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
  networks:
    - 8llow8llowme-net

networks:
  8llow8llowme-net:
    name: 8llow8llowme-net
    driver: bridge
