server:
  port: ${SERVER_PORT}
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    url: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_SCHEMA_NAME}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username: ${DB_USERNAME}                   # 데이터베이스 계정명
    password: ${DB_PASSWORD}         # 데이터베이스 계정 비밀번호

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
        jdbc:
          batch_size: 100
        default_batch_fetch_size: 100

openapi:
  transport:
    url: ${OPENAPI_TRANSPORT_URL}
    service-key: ${OPENAPI_TRANSPORT_SERVICE_KEY}